name: Run Azure Login with OpenID Connect
on: [push]

permissions: write-all
      
jobs: 
  build-and-deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./azuredeploy.json
        parameters: storageAccountType=Standard_LRS

        # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}